name: CI

on:
  push:
    branches: [main]
    tags: [ 'v*' ]
    paths:
      - ".github/workflows/ci.yml"
      - "frontend/**"
      - "backend/**"
      - "!backend/bin/**"
      - "!backend/scripts/**"
  
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "frontend/**"
      - "backend/**"
      - "!backend/bin/**"
      - "!backend/scripts/**"

jobs:
  backend:
    name: Backend Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache-dependency-path: backend

      - name: test and build backend
        run: |
          go test -race -timeout=60s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
          go build -race ./...
        working-directory: backend/app
        env:
          TZ: "Europe/Moscow"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.7.2
          args: --config=.golangci.yml
          working-directory: backend

      - name: submit coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -flagname="backend" -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        working-directory: backend
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  frontend:
    name: Frontend Test & Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10    

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: 'frontend/pnpm-lock.yaml'

      - name: install dependencies
        run: pnpm install

      - name: checks
        run: mise run //frontend:checks

      - name: tests
        run: mise run //frontend:tests